[package]
authors = ["Pierre-Étienne Meunier <pe@pijul.org>"]
description = "Deal with SSH keys: load them, decrypt them, call an SSH agent."
documentation = "https://docs.rs/russh-keys"
edition = "2018"
homepage = "https://pijul.org/russh"
include = [
  "Cargo.toml",
  "src/lib.rs",
  "src/pem.rs",
  "src/agent/mod.rs",
  "src/agent/msg.rs",
  "src/agent/server.rs",
  "src/agent/client.rs",
  "src/bcrypt_pbkdf.rs",
  "src/blowfish.rs",
  "src/encoding.rs",
  "src/format/mod.rs",
  "src/format/openssh.rs",
  "src/format/pkcs5.rs",
  "src/format/pkcs8.rs",
  "src/key.rs",
  "src/signature.rs",
]
keywords = ["ssh"]
license = "Apache-2.0"
name = "russh-keys"
repository = "https://nest.pijul.com/pijul/russh"
version = "0.22.0-beta.7"

[dependencies]
aes = { version = "0.8", optional = true }
bcrypt-pbkdf = { version = "0.6", optional = true }
bit-vec = "0.6"
cbc = { version = "0.1", optional = true }
ctr = { version = "0.9", optional = true }
block-padding = { version = "0.3", features = ["std"], optional = true }
byteorder = "1.4"
data-encoding = "2.3"
dirs = "3.0"
ed25519-dalek = { version = "1.0", optional = true }
futures = "0.3"
hmac = { version = "0.12", optional = true }
inout = { version = "0.1", features = ["std"] }
log = "0.4"
md5 = "0.7"
num-bigint = "0.4"
num-integer = "0.1"
openssl = { version = "^0.10.40", optional = true }
pbkdf2 = { version = "0.11", optional = true }
rand = "0.7"
rand_core = { version = "0.5", features = ["std"] }
russh-cryptovec = { version = "0.7.0-beta.1", path = "../cryptovec" }
serde = "1.0"
serde_derive = "1.0"
sha2 = "0.10"
thiserror = "1.0"
tokio = { version = "1.17.0", features = [
  "io-util",
  "rt-multi-thread",
  "time",
  "net",
] }
tokio-stream = { version = "0.1", features = ["net"] }
yasna = { version = "0.4.0", features = ["bit-vec", "num-bigint"] }

[features]
default = ["rs-crypto"]
vendored-openssl = ["openssl", "openssl/vendored"]
rs-crypto = [
  "dep:aes",
  "dep:bcrypt-pbkdf",
  "dep:cbc",
  "dep:ctr",
  "dep:block-padding",
  "dep:hmac",
  "dep:pbkdf2",
  "dep:ed25519-dalek",
]

[dev-dependencies]
env_logger = "0.8"
tempdir = "0.3"
